### PR TITLE
Fix handling resuming audio after interruptions

### LINKED ISSUE #151: Audio not pausing when Apple Maps giving directions
Apple Maps has a feature that allows apps that designate themselves as “spoken word audio” to be automatically paused when Maps is speaking directions in navigation. BookPlayer is not pausing when directions are being said in Maps, instead continuing to play in the background.

### PR DESCRIPTION
**Pull request by GianniCarlo**
This should fix #151 (tested with Google Maps) and #155

### CODE REVIEW

File: BookPlayer/Player/PlayerViewController.swift [hunk 1]
```diff
@@ -185,7 +185,7 @@ class PlayerViewController: UIViewController, UIGestureRecognizerDelegate {
             },
             onEnd: { (_ cancelled: Bool) -> Void in
                 if !cancelled {
-                    PlayerManager.shared.stop()
+                    PlayerManager.shared.pause()
```
Comment (GianniCarlo) [inline BookPlayer/Player/PlayerViewController.swift]: thoughts?

Comment (pichfl) [reply BookPlayer/Player/PlayerViewController.swift]: Totally for it. Given our current interaction model, `stop()` is used only when a book is about to be deleted. Or when it's paused and the mini player is dismissed. Pausing makes much more sense for the timer :)
